name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hola Emma!
    - name: Run a multi-line script
      run: |
        echo mua
        echo mua
